### ISSUE TITLE
Video decoding with Cidre slower than using Swift

### ISSUE THREAD

**Issue by Brendonovich** [yury/cidre#33]
I've implemented basic video decoding using `AVAssetReader` in [this repo](https://github.com/Brendonovich/avfoundation-decoding), both using Swift and using Cidre.
On my machine, `cargo run --bin swift` completes in ~0.38 seconds, wheras `cargo run --bin cidre` completes in ~1.4 seconds.
Would you know why this is? I'm guessing I've either made a mistake, or Swift is able to do extra optimisations that Rust + Cidre can't.
Thanks for all your work on this library, it's the cleanest Apple bindings I've found!

**Comment by yury** [comment]
Hello,

I took a look.

Main performance hit is 
```rust
reader_track_output.set_always_copies_sample_data(true); // <- swift version set this prop to `false`
```

Another improvement - use unsafe _throws version of `next_sample_buf` method and use try catch block around the loop:

```rust
ns::try_catch(|| {
     while let Some(sample_buf) = unsafe { reader_track_output.next_sample_buf_throws() } {
         if let Some(_) = sample_buf.image_buf() {
             i += 1;
         }
     }
})
.unwrap();
```

With this changes I got:
- `cargo run --release --bin cidre` - `decoded 492 frames in 374.407125ms`
- `cargo run --release --bin swift` - `decoded 492 frames in 0.374851709 seconds`

Sometimes swift a little bit faster. Sometimes rust version is a little bit faster.


PS:

Better way to construct settings for reader:

```rust
    let settings = ns::Dictionary::with_keys_values(
        &[cv::pixel_buffer::keys::pixel_format().as_ns()],
        &[cv::PixelFormat::_420V.to_cf_number().as_ns().as_id_ref()],
    );

    let mut reader_track_output =
        av::AssetReaderTrackOutput::with_track(track, Some(&settings)).unwrap();
```

**Comment by Brendonovich** [comment]
Thankyou! Silly mistake on my part. Now to make it work with all our other code 😅

**Comment by yury** [comment]
You can reduce build time if you disable default-features and include only required:

```toml
[dependencies]
cidre = { git = "https://github.com/yury/cidre", default-features=false, features = ["av", "cm", "dispatch", "async"] }
tokio = { version = "1.43.0", default-features=false, features = ["macros", "rt", "rt-multi-thread"] }
```
